version: '2.1'

services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/volumes/nginx/html:/usr/share/nginx/html
      - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/volumes/nginx/html:/usr/share/nginx/html
      - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/volumes/nginx/html:/usr/share/nginx/html
      - /srv/volumes/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      timeout: 5s
      retries: 20
    volumes:
      - 'lobsters_database:/var/lib/mysql'
  app:
    image: utensils/lobsters:latest
    build:
      context: .
      args:
        DEVELOPER_BUILD: "false"
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME="Example News"
      - RAILS_ENV=development
      - LOBSTER_HOSTNAME=domain
      - VIRTUAL_HOST=domain
      - LETSENCRYPT_HOST=domain
      - RAILS_MAX_THREADS=5
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
      #proxy:
      #  condition: service_started

volumes:
  lobsters_database:
    driver: local

networks:
  default:
    external:
      name: webproxy
